### ISSUE TITLE
Database update warning but no updates apparently required

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/uc_price_per_role#13]
I saw a status message indicating Database updates were required; yet running update.php reported no issues.

Trying to find the cause, I was led to the suggestion at: 

https://forum.backdropcms.org/comment/5571#comment-5571

and this provided more detail:

The uc_price_per_role module (and possibly others) has database schema updates to install

I checked the system table and saw that the schema_version for uc_price_per_role was set to -1. I manually changed this to 1000 to see if it fixed the problem, and it did. No more 'database update required' message.

I don't know if this was caused by the uc_price_per_role module, or is a consequence of something else in my Backdrop site. It is a site that was upgraded from D7, but the uc_price_per_role module wasn't used there (I only found out about it after upgrading the site to Backdrop).

I'm reporting this issue here in case it affects anyone else, and/or is caused by something in the code that means the schema_version wasn't properly set.

The module is working perfectly well for me - it is only the upgrade status issue that caused any concern.

**Comment by bugfolder** [comment]
In order to look into this usefully, it will be necessary to reproduce it. So, here's what I understand from your report that you did:

* You had a D7 Ubercart site that did not have uc_price_per_role installed.
* You upgraded the site to Backdrop.
* You then installed uc_price_per_role.
* The update warnings appeared in the status report.

Is that correct? If so, did you run into any issues with the above, or did everything complete routinely?

Also, what PHP version were you running?

**Comment by nattywebdev** [comment]
Not quite right. The sequence was:

1. I had a D7 Commerce site, which I disabled and uninstalled all Commerce modules. 
2. I upgraded to Backdrop and installed Ubercart. 
3. Finally, I added uc_price_per_role.
4. I then noticed the warning to update the database in the status report.

No particular problems, and the database status warning didn't appear before I added uc_price_per_role.

I have php 7.4 on both dev and staging servers.

**Comment by bugfolder** [comment]
This is a puzzling situation. The meaning of `schema_version` in the `system` table is:

* `-1` for modules that were previously enabled and are now uninstalled.
* `0` for modules that were previously or are currently enabled but have no `hook_update_N()` implementations.
* `1000`+ for modules that were previously or are currently and have hook_update_N() implementations (value is the latest update that has been run).

So, having a `schema_version` of -1 is perfectly OK, but it should be paired with `status` = 0.

I can achieve the scenario you described by setting `status` = 1, `schema_version` = -1 (which should never arise in practice). That gives the "you need to run db updates" warning, no updates actually run, and the warning doesn't go away.

None of this `system`-table twiddling is done by anything in `uc_price_per_role` module. So I think this module was just an unlucky bystander in some incomplete upgrade running, or something similar. Or an incomplete uninstallation.

Since you describe uc_price_per_role as functioning, that suggests that its tables exist (otherwise, your site would likely die painfully under usage). So that suggests that the module installed properly, but Backdrop never updated the `schema_version` from its uninstalled value. I've gone through several versions of installing, disabling, uninstalling, and re-enabling (with and without its `system` table row) and haven't been able to recreate this scenario without going into the `system` table and manipulating it directly.

**Comment by nattywebdev** [comment]
Thanks for looking into it so thoroughly. I'm very happy to accept this is a unique situation caused by my particular set of circumstances. I'm delighted that this module exists in Backdrop as it does exactly what I need. Feel free to close this issue.
