### ISSUE TITLE
Sell price changes suddenly to one of the role prices.

### ISSUE THREAD

**Issue by samgreco** [backdrop-contrib/uc_price_per_role#9]
I don't know exactly when or how, but prices got whacked on our site.

We have a field for Dealer pricing that is hidden from anonymous users.  They see the sell price, which I've renamed through a hook to MAP Price.  Don't know if that matters?  Suddenly (seemingly), all of the Sell (MAP) prices are showing the price-per-role Dealer price.  Very bad.

Do you have ANY thoughts on what could possible cause this?

**Comment by bugfolder** [comment]
If you edit a product, in the Product Information vertical tab, you'll see "List price," "Cost," and "Default sell price," followed by all of the role-specific prices.

1. Have the List and Default sell price been changed to one of the role prices (.e.,g the Dealer price)?

2. Does a person with Dealer role have the ability to edit products in any way?

I ask because I've seen situations where if the store admin has a special discounted role, editing the product can set the default price to the role price (unless the admin has taken care to override their role using the "Price Roles" block). But I don't know of a way this could happen to every product.

**Comment by bugfolder** [comment]
Some more thoughts.

First, take a look at Admin > Content, filtering to your products, looking in particular at the last "Updated" date. Any patterns or anomalies there could give you a clue as to when (and therefore how) this happened.

Second, do you have any sort of automatic product updating that happens via cron (e.g., automatic removal of a "New" tag), or anything like that (and/or do the modification dates match times of day that cron runs?) If cron is running as a privileged user, that could result in the scenario described by my previous comment.

**Comment by samgreco** [comment]
> 2\. Does a person with Dealer role have the ability to edit products in any way?

Nailed it!  I have the Dealer Role and was working on some clean up and did some other stuff and resaved EVERY PRODUCT NODE!

Thanks for the very quick reply.  I have now removed any other roles I had.  And anyone else with admin like permissions.

**Comment by bugfolder** [comment]
Glad to have identified the problem.

We really need to find a fix for this behavior of the module, so let's leave this issue open.

**Comment by bugfolder** [comment]
Here's some investigation. Let's assume the current user has a special role price and some admin abilities.

If we edit the product on its edit page at /node/N/edit and change the default price to something, it sticks.

However, if somewhere in code, we modify the node via this idiom, the default price gets set incorrectly to the special role price:

```
$node = node_load(N);
// make some edits to $node
$node->save();
```

This is because when the node is loaded, via `uc_proce_per_role_node_load()` (`hook_node_load()`),  `uc_price_per_role` replaces `$node->sell_price` with the role-specific price, and stashes the original price in `$node->roleindependent_sell_price`.

In `uc_price_per_role_prepare()` (`hook_node_prepare()`), we restore the original price before displaying it on the add/edit form. Seems like we should do that before saving (e.g., in `hook_node_presave()`) in most cases, but in a way that still allows admins to change the default price.
